---

services:
  mysql:
    image: mariadb:12.0.2
    environment:
      MARIADB_ROOT_PASSWORD: test
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal

volumes:
  mariadb-data:
networks:
  internal:
