[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["mysql", "runtime-tokio"] }
thiserror = "2.0.16"
