---
name: Pi-Bot Build Image

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-pi-bot:
    name: Build Pi-Bot Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Log into registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/scioly/pi-bot

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: pi-bot/Dockerfile
          push: true
          tags: >-
            ghcr.io/${{ github.repository_owner }}/pi-bot:
            pi-bot-${{ github.sha }}
          build-args: >
            version=
            ${{ steps.date.outputs.date }}-${{ steps.vars.outputs.sha_short }}

  build-web-server:
    name: Build Web Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Log into registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/scioly/pi-bot

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: web-server/Dockerfile
          push: true
          tags: >-
            ghcr.io/${{ github.repository_owner }}/pi-bot:
            web-server-${{ github.sha }}
